agg.h File Reference
Functions
gdouble agg_bernstein_basis_eval (gint n, gint r, gdouble x)
 agg_section_t * agg_section_new (gint oumax, gint olmax)
gdouble agg_section_eval (agg_section_t *s, gdouble x)
gdouble agg_section_diff (agg_section_t *s, gdouble x)
gint agg_section_copy (agg_section_t *dest, agg_section_t *src)
gint agg_section_set_circle (agg_section_t *s)
gint agg_section_set_aerofoil (agg_section_t *s, gdouble eta, gdouble th, gdouble yte)
gint agg_section_parse (agg_section_t *s, gchar *name, agg_variable_t *p, gint np)
gint agg_sections_list (FILE *f)
 agg_transform_operator_t * agg_transform_operator_new (void)
 agg_transform_t * agg_transform_new (gint nopmax)
gint agg_transform_variable_add (agg_transform_t *T, gchar *var, gchar *def, gdouble val)
gint agg_transform_add_global_variables (agg_transform_t *T, agg_variable_t *global, gint nglobal)
gint agg_transform_expressions_compile (agg_transform_t *T)
gint agg_transform_variables_eval (agg_transform_t *T)
gint agg_transform_variables_write (FILE *f, agg_transform_t *T, gboolean write_defs)
gint agg_transform_operator_add (agg_transform_t *T, agg_operation_t op, gdouble *p, gchar **expr, gint np)
gint agg_transform_operators_write (FILE *f, agg_transform_t *T)
gint agg_transform_apply (agg_transform_t *T, gdouble *xin, gdouble *xout)
gint agg_transform_operator_apply (agg_transform_operator_t *op, gdouble *xin, gdouble *xout)
gint agg_transform_axes (agg_axes_t axes, gdouble *xin, gdouble *xout)
gint agg_transform_parse (agg_transform_t *T, gchar *name, agg_variable_t *p, gint np)
 agg_axes_t agg_axes_parse (gchar *str)
gint agg_variable_write (FILE *f, agg_variable_t *v)
gint agg_expression_data_variable_add (agg_expression_data_t *d, agg_variable_t *v)
gpointer agg_expression_compile (gchar *e, agg_expression_data_t *d)
gdouble agg_expression_eval (gpointer e)
gint agg_expression_data_compile (agg_expression_data_t *d)
gint agg_expression_data_eval (agg_expression_data_t *d)
 agg_surface_t * agg_surface_new (gint nsmax)
gint agg_surface_section_add (agg_surface_t *S, agg_section_t *s, gdouble u)
gint agg_surface_weights_make (agg_surface_t *S)
gint agg_surface_section_interp (agg_surface_t *S, gdouble u, agg_section_t *s)
gint agg_surface_point_eval (agg_surface_t *S, gdouble u, gdouble v, gdouble *x, agg_surface_workspace_t *w)
gint agg_surface_point_diff (agg_surface_t *S, gdouble u, gdouble v, gdouble *x, gdouble *xu, gdouble *xv, agg_surface_workspace_t *w)
agg_surface_workspace_t * agg_surface_workspace_new (void)
gdouble agg_naca_four (gdouble t, gdouble p, gdouble m, gdouble x)
gint agg_patch_map (agg_patch_t *p, gdouble s, gdouble t, gdouble *u, gdouble *v)
gint agg_patch_st_correct (agg_patch_t *P, gdouble *st)
gint agg_patch_parse (agg_patch_t *P, agg_variable_t *p, gint np)
gint agg_patch_surface_diff (agg_patch_t *P, gdouble s, gdouble t, gdouble *xu, gdouble *xv, gdouble *xs, gdouble *xt)
 agg_intersection_t * agg_intersection_new (gint nstmax)
gint agg_surface_patch_intersection (agg_intersection_t *inter, agg_surface_t *S1, agg_patch_t *P1, agg_surface_t *S2, agg_patch_t *P2, agg_surface_blend_t *B, agg_surface_workspace_t *w)
gint agg_intersection_curve_write (FILE *f, agg_intersection_t *inter, agg_surface_workspace_t *w)
gint agg_intersection_bbox_set (agg_intersection_t *inter)
gint agg_intersection_resample (agg_intersection_t *inter, gint nsp, gint pps, agg_intersection_t *resample, agg_surface_workspace_t *w)
gint agg_patch_clip_eval (agg_patch_clipping_t *c, gdouble u, gdouble *s, gdouble *t)
gint agg_clipping_orient (agg_patch_clipping_t *c1, agg_patch_t *P1, agg_surface_t *S1, agg_patch_clipping_t *c2, agg_patch_t *P2, agg_surface_t *S2, agg_surface_workspace_t *w)
 agg_mesh_t * agg_mesh_new (gint npmax, gint nspmax, gint nemax)
gint agg_mesh_write_gmsh (FILE *f, agg_mesh_t *w, gchar *len, gint offp, gint offsp, gint offs, gboolean opencascade)
gint agg_mesh_spline_ends (agg_mesh_t *w, gint s, gint *p0, gint *p1)
gint agg_mesh_spline_interp_points (agg_mesh_t *w, gint s, gint p0, gint p1, gint pps, agg_surface_workspace_t *ws)
gboolean agg_mesh_splines_connected (agg_mesh_t *w, gint i0, gint i1, gint *p)
gint agg_mesh_element_add (agg_mesh_t *w, gint s0, gint s1, gint s2, gint s3)
gint agg_mesh_surface_add_triangle (agg_mesh_t *msh, gint isurf, gchar *args, gint pps, agg_surface_workspace_t *w)
gint agg_mesh_surface_blend_add (agg_mesh_t *m, gint iB, gint nsec, gint pps, agg_surface_workspace_t *w)
gint agg_mesh_surface_add_grid (agg_mesh_t *m, gint iS, gint nsec, gint nsp, gint pps, agg_surface_workspace_t *w)
gint agg_mesh_spline_from_endpoints (agg_mesh_t *w, gint p0, gint p1)
gint agg_mesh_surface_point_add (agg_mesh_t *w, gint surf, gdouble s, gdouble t, agg_surface_workspace_t *ws)
gint agg_mesh_body (agg_mesh_t *m, agg_body_t *b, gint pps, agg_surface_workspace_t *w)
gint agg_mesh_element_nodes (agg_mesh_t *m, gint e, gint *nodes, gint *nnodes, gint *s)
 agg_body_t * agg_body_new (gint ngmax, gint nsmax)
gint agg_body_global_add (agg_body_t *b, gchar *var, gchar *def, gdouble val)
gint agg_body_globals_write (FILE *f, agg_body_t *b)
gint agg_body_globals_compile (agg_body_t *b)
gint agg_body_globals_eval (agg_body_t *b)
gint agg_body_read (agg_body_t *b, gchar *file, gboolean echo)
gint agg_body_surfaces_list (FILE *f, agg_body_t *b)
 agg_grid_t agg_grid_parse (gchar *str)
gint agg_surface_blend_evaluate (agg_surface_blend_t *B, gdouble s, gdouble t, gdouble *x, agg_surface_workspace_t *w)
gint agg_hermite_eval (gdouble s, gdouble *H)
Variables
typedef agg_body_t
#define agg_variable_name(v)
name of an agg_variable_t
#define agg_variable_definition(v)
definition of an agg_variable_t, as as string, or NULL for numerical constants
#define agg_variable_evaluator(v)
evaluator for the compiled expression for the variable, or NULL for numerical constants
#define agg_variable_value(v)
numerical value of the variable (which may change on upon reevaluation of the expression)
typedef agg_variable_t
#define agg_section_type(s)
agg_section_type_t of an agg_section_t
#define agg_section_close(s)
TRUE if an agg_section_t needs to be closed.
#define agg_section_eta_left(s)
value of $\eta_{1}$ controlling curvature around $x=0$
#define agg_section_eta_right(s)
value of $\eta_{2}$ controlling curvature around $x=1$
#define agg_section_coefficient_upper(s, i)
$i$th coefficient in Bernstein expansion of upper part of a section
#define agg_section_coefficient_lower(s, i)
$i$th coefficient in Bernstein expansion of lower part of a section
#define agg_section_order_upper(s)
order of Bernstein expansion in upper part of section
#define agg_section_order_lower(s)
order of Bernstein expansion in lower part of section
#define agg_section_order_upper_max(s)
maximum order of Bernstein expansion in upper part of section
#define agg_section_order_lower_max(s)
maximum order of Bernstein expansion in lower part of section
#define agg_section_trailing_edge_upper(s)
semi-thickness of upper part of trailing edge on aerofoil section
#define agg_section_trailing_edge_lower(s)
semi-thickness of lower part of trailing edge on aerofoil section
enum agg_section_type_t { AGG_SECTION_UNDEFINED = 0
, AGG_SECTION_AEROFOIL = 1
, AGG_SECTION_ELLIPSE = 2
 }
typedef agg_section_t
typedef agg_expression_data_t
#define agg_transform_operator_operation(op)
operation performed by an agg_transform_operator_t
#define agg_transform_operator_parameters(op)
parameters of agg_variable_t for an agg_transform_operator_t
#define agg_transform_operator_parameter(op, i)
$i$th parameter for agg_transform_operator_t
#define agg_transform_operator_parameter_number(op)
number of parameters for the agg_transform_operator_t
#define agg_transform_operator_func(op)
function called to execute the transform operation
#define agg_transform_operator(T, i)
$i$th operation of an agg_transform_t
#define agg_transform_operator_number(T)
number of operations in an agg_transform_t
#define agg_transform_operator_number_max(T)
maximum number of operations in an agg_transform_t
#define agg_transform_variable(T, i)
$i$th variable in an agg_transform_t
#define agg_transform_variable_number(T)
number of variables in an agg_transform_t
enum agg_operation_t {
 AGG_TRANSFORM_UNDEFINED = 0
, AGG_TRANSFORM_ROTATE = 1
, AGG_TRANSFORM_SHRINK = 2
, AGG_TRANSFORM_TRANSLATE = 3
,
 AGG_TRANSFORM_SCALE = 4
, AGG_TRANSFORM_SCALE_X = 5
, AGG_TRANSFORM_SCALE_Y = 6
 }
typedef agg_transform_operator_t
typedef agg_transform_t
enum agg_axes_t { }
enum agg_grid_t { AGG_GRID_UNDEFINED = 0
, AGG_GRID_REGULAR = 1
, AGG_GRID_TRIANGLE = 2
 }
typedef agg_surface_t
enum agg_patch_mapping_t { AGG_PATCH_BILINEAR = 0
, AGG_PATCH_SPHERICAL = 1
, AGG_PATCH_TUBULAR = 2
 }
typedef agg_patch_t
typedef agg_intersection_t
typedef agg_mesh_t
Enumeration Type Documentation
agg_grid_t
enum agg_grid_t
Specification of surface grid generation algorithms
Enumerator
AGG_GRID_UNDEFINED undefined (generates an error)
AGG_GRID_REGULAR regular quadrilaterals in parametric space
AGG_GRID_TRIANGLE mesh generated using Triangle code
agg_patch_mapping_t
enum agg_patch_mapping_t
Mappings from $(s,t)$ on a patch to $(u,v)$ on a surface
Enumerator
AGG_PATCH_BILINEAR bilinear mapping between corners
AGG_PATCH_SPHERICAL mapping to surface of sphere
AGG_PATCH_TUBULAR mapping to surface of open cylinder
Function Documentation
agg_axes_parse()
 agg_axes_t agg_axes_parse (gchar * str)
Parse a string specifying an axis change on a surface.
Parameters
str axis string to parse
Returns
agg_axes_t corresponding to str, or AGG_AXES_UNDEFINED.
agg_body_global_add()
gint agg_body_global_add (agg_body_t * b, gchar * var, gchar * def, gdouble val)
Add a global variable to an agg_body_t
Parameters
b body to which variable should be added;
var name of variable;
def string expression defining variable (can be NULL);
val value of variable (set constant if expr is NULL).
Returns
0 on success.
References agg_variable_definition, agg_variable_name, agg_variable_t, and agg_variable_value.
agg_body_globals_compile()
gint agg_body_globals_compile (agg_body_t * b)
Compile expressions for global variables in an agg_body_t. This function should be called before evaluating any variables in the body or its surfaces.
Parameters
b an agg_body_t containing definitions of global variables.
Returns
0 on success.
References agg_expression_compile(), agg_expression_data_t, agg_expression_data_variable_add(), agg_variable_definition, agg_variable_evaluator, and agg_variable_t.
agg_body_globals_eval()
gint agg_body_globals_eval (agg_body_t * b)
Evaluate global variables defined in an agg_body_t. This function should be called before evaluating points on the surfaces which make up the body.
Parameters
b an agg_body_t containing global variables.
Returns
0 on success.
References agg_expression_data_eval(), agg_expression_eval(), agg_variable_definition, agg_variable_evaluator, agg_variable_t, and agg_variable_value.
agg_body_globals_write()
gint agg_body_globals_write (FILE * f, agg_body_t * b)
Write a body's global variables, their definitions (if given), and values to file
Parameters
f output file;
b agg_body_t whose global variables are to be written
Returns
0 on success.
References agg_variable_definition, agg_variable_name, agg_variable_t, and agg_variable_value.
agg_body_read()
gint agg_body_read (agg_body_t * b, gchar * file, gboolean echo)
Read an agg_body_t from file
Parameters
b body to which data in file are to be added;
file name of file in .agg format;
echo if TRUE, echo progress to stderr.
Returns
0 on success.
References agg_section_new().
agg_body_surfaces_list()
gint agg_body_surfaces_list (FILE * f, agg_body_t * b)
Write the names of a body's surfaces to file
Parameters
f output file stream;
b an agg_body_t whose surfaces are to be listed.
Returns
0 on success.
agg_clipping_orient()
gint agg_clipping_orient (agg_patch_clipping_t * c1, agg_patch_t * P1, agg_surface_t * S1, agg_patch_clipping_t * c2, agg_patch_t * P2, agg_surface_t * S2, agg_surface_workspace_t * w)
Set orientation of two clipping curves so that they are traversed in the same sense in physical space. The test is performed by evaluating approximate normals to the curve planes (this assumes that the curves are not too far from planar) and checking the normals are approximately parallel, using the sign of the scalar product. If necessary, the orientation of one curve is switched, with priority given to changing the orientation of a closed curve, corresponding to a hole in a surface, over a cut on constant $s$ or $t$. If curves are not mutually oriented and are both constant parameter cuts, execution stops with an error (until I can decide how best to handle this case).
Parameters
c1 first patch clipping;
P1 first parametric patch;
S1 first physical surface;
c2 second patch clipping;
P2 second parametric patch;
S2 second physical surface;
w workspace for surface point evaluation.
Returns
0 on success.
References agg_patch_clip_eval(), agg_patch_map(), and agg_surface_point_eval().
agg_expression_compile()
gpointer agg_expression_compile (gchar * e, agg_expression_data_t * d)
Compile a symbolically defined expression, for future evaluation
Parameters
e the expression to be compiled;
d structure holding variable data.
Returns
pointer to compiled expression.
Referenced by agg_body_globals_compile(), and agg_transform_expressions_compile().
agg_expression_data_compile()
gint agg_expression_data_compile (agg_expression_data_t * d)
Compile expressions in an expression data structure, for future evaluation
Parameters
d an agg_expression_data_t
Returns
0 on success.
agg_expression_data_eval()
gint agg_expression_data_eval (agg_expression_data_t * d)
Evaluate expressions in an expression data structure, making the values available for other calculations.
Parameters
d an agg_expression_data_t whose expressions are to be evaluated.
Returns
0 on success.
Referenced by agg_body_globals_eval(), and agg_transform_variables_eval().
agg_expression_data_variable_add()
gint agg_expression_data_variable_add (agg_expression_data_t * d, agg_variable_t * v)
Add a variable to an agg_expression_data_t.
Parameters
d agg_expression_data_t to have variable added;
v a variable to be added to d; this may depend on variables already in d, but not on variables yet to be added.
Returns
0 on success.
References agg_variable_definition, agg_variable_name, and agg_variable_value.
Referenced by agg_body_globals_compile(), agg_transform_add_global_variables(), and agg_transform_expressions_compile().
agg_expression_eval()
gdouble agg_expression_eval (gpointer e)
Evaluate a compiled expression
Parameters
e a pointer to a tinyexpr expression
Returns
the value of e.
Referenced by agg_body_globals_eval(), and agg_transform_variables_eval().
agg_grid_parse()
 agg_grid_t agg_grid_parse (gchar * str)
Parse a string specifying a surface grid type
Parameters
str grid string to parse
Returns
agg_grid_t corresponding to str, or AGG_GRID_UNDEFINED.
References AGG_GRID_REGULAR, AGG_GRID_TRIANGLE, and AGG_GRID_UNDEFINED.
agg_hermite_eval()
gint agg_hermite_eval (gdouble s, gdouble * H)
Evaluate Hermite smoothing polynomials
Parameters
s argument of polynomials;
H on exit contains $H_{i}(s)$, $1\leq i\leq4$.
Returns
0 on success.
agg_intersection_bbox_set()
gint agg_intersection_bbox_set (agg_intersection_t * inter)
Calculate the bounding box of an intersection curve in the two surface patch mappings.
Parameters
inter intersection curve whose bounding boxes are to be set.
Returns
0 on success.
agg_intersection_curve_write()
gint agg_intersection_curve_write (FILE * f, agg_intersection_t * inter, agg_surface_workspace_t * w)
Write an intersection curve to file in the form
[ $x$ $y$ $z$ $s_{1}$ $t_{1}$ $s_{2}$ $t_{2}$]
where $(x,y,z)$ are physical coordinates and $(s_{i},t_{i})$ are parametric coordinates on the respective surface patches (not the surfaces proper)
Parameters
f output file stream;
inter intersection curve to write;
w workspace for surface evaluation.
Returns
0 on success.
agg_intersection_new()
 agg_intersection_t * agg_intersection_new (gint nstmax)
Allocate a new surface intersection structure.
Parameters
nstmax maximum number of points on intersection curve.
Returns
newly allocated agg_intersection_t.
References agg_intersection_t.
agg_intersection_resample()
gint agg_intersection_resample (agg_intersection_t * inter, gint nsp, gint pps, agg_intersection_t * resample, agg_surface_workspace_t * w)
Resample an intersection curve to (approximately) evenly spaced points in the mapping patch.
Parameters
inter an intersection curve;
nsp number of splines in the resampled curve;
pps number of points per spline in the resampled curve;
resample on output contains the resampled intersection data;
w workspace for surface evaluation.
Returns
0 on success.
agg_mesh_body()
gint agg_mesh_body (agg_mesh_t * m, agg_body_t * b, gint pps, agg_surface_workspace_t * w)
Generate a mesh for surfaces and surface blends on a body
Parameters
m mesh to generate;
b body containing surface data;
pps points per spline on element edges;
w workspace for point evaluation.
Returns
0 on success.
References agg_intersection_t.
agg_mesh_element_add()
gint agg_mesh_element_add (agg_mesh_t * m, gint s0, gint s1, gint s2, gint s3)
Add an element to a mesh.
Parameters
m an agg_mesh_t to have an element added.
s0 index of first spline of element;
s1 index of second spline of element;
s2 index of third spline of element;
s3 index of fourth spline of element (if zero, a three-sided element is added)
Returns
0 on success.
agg_mesh_element_nodes()
gint agg_mesh_element_nodes (agg_mesh_t * m, gint e, gint * nodes, gint * nnodes, gint * s)
Find the oriented nodes of an element in an agg_mesh_t
Parameters
m mesh containing elements to be queried;
e element index;
nodes on exit contains nodes of element in cyclic order;
nnodes on exit contains number of nodes in nodes;
s index in m of surface containing nodes.
Returns
0 on success.
agg_mesh_spline_ends()
gint agg_mesh_spline_ends (agg_mesh_t * m, gint s, gint * p0, gint * p1)
Find the indices of the end points of a spline in a mesh
Parameters
m mesh containing the splines;
s index of spline;
p0 on exit, index of one end point of spline s;
p1 on exit, index of other end point of spline s.
Returns
0 on success
Referenced by agg_mesh_splines_connected().
agg_mesh_spline_from_endpoints()
gint agg_mesh_spline_from_endpoints (agg_mesh_t * m, gint p0, gint p1)
Find a spline from its endpoints
Parameters
m a mesh containing a set of splines;
p0 index of a point of m;
p1 index of a point of m.
Returns
index of a spline which has endpoints p0 and p1, or 0 if there is no such spline.
agg_mesh_spline_interp_points()
gint agg_mesh_spline_interp_points (agg_mesh_t * m, gint s, gint p0, gint p1, gint pps, agg_surface_workspace_t * w)
Generate a spline by interpolating mapping between two existing points.
Parameters
m an agg_mesh_t;
s index in m of surface to use for interpolation;
p0 index of first point of new spline;
p1 index of end point of new spline;
pps total number of points on new spline;
w workspace for surface evaluation.
Returns
0 on success.
agg_mesh_splines_connected()
gboolean agg_mesh_splines_connected (agg_mesh_t * m, gint i0, gint i1, gint * p)
Check if two splines in an agg_mesh_t are connected.
Parameters
m an agg_mesh_t;
i0 index of first spline to check;
i1 index of second spline to check;
p on exit, set to index of common point of splines i0 and i1.
Returns
TRUE if splines have an end point in common.
References agg_mesh_spline_ends().
agg_mesh_surface_add_grid()
gint agg_mesh_surface_add_grid (agg_mesh_t * m, gint iS, gint nsec, gint nsp, gint pps, agg_surface_workspace_t * w)
Add surface elements to a mesh, on a square grid in the parametric space
Parameters
m mesh to add elements to;
iS index of surface in surface list of m;
nsec number of sections on surface;
nsp number of splines per section;
pps points per spline on sections;
w workspace for point evaluation.
Returns
0 on success.
References agg_patch_t.
agg_mesh_surface_add_triangle()
gint agg_mesh_surface_add_triangle (agg_mesh_t * msh, gint isurf, gchar * args, gint pps, agg_surface_workspace_t * w)
Add a parametric surface to a mesh, working round clipped parts of patch, using Christian Woltering's library version of Jonathan Shewchuk's Triangle code:
 https://github.com/wo80/Triangle/ https://www.cs.cmu.edu/~quake/triangle.html
Parameters
msh a mesh to have a surface added;
isurf index of surface in mesh surface list;
args argument string to pass to triangle;
pps points per spline;
w workspace for surface evaluation.
Returns
0 on success.
References agg_patch_t.
agg_mesh_surface_blend_add()
gint agg_mesh_surface_blend_add (agg_mesh_t * m, gint iB, gint nsec, gint pps, agg_surface_workspace_t * w)
Add elements from a surface blend to a mesh
Parameters
m mesh to add surface elements to;
iB index of surface blend in m;
nsec number of sections on blend;
pps points per spline on element edges;
w workspace for point evaluation
Returns
0 on success.
agg_mesh_surface_point_add()
gint agg_mesh_surface_point_add (agg_mesh_t * m, gint surf, gdouble s, gdouble t, agg_surface_workspace_t * w)
Add a point to a mesh
Parameters
m mesh to have point added;
surf index in m of surface on which to evaluate point;
s coordinate on patch for surface surf;
t coordinate on patch for surface surf;
w workspace for surface evaluation.
Returns
index of newly added point.
References agg_patch_t, and agg_surface_t.
agg_mesh_write_gmsh()
gint agg_mesh_write_gmsh (FILE * f, agg_mesh_t * m, gchar * len, gint offp, gint offsp, gint offs, gboolean opencascade)
Write a agg_mesh_t to file in GMSH .geo format.
Parameters
f output file stream;
m mesh to write to file;
len string to include point definitions for local length scale;
offp point index offset (added to point indices);
offsp spline index offset (added to spline indices);
offs surface index offset (added to GMSH surface indices);
opencascade if TRUE, assume OpenCascade engine is being used.
Returns
0 on success.
agg_patch_clip_eval()
gint agg_patch_clip_eval (agg_patch_clipping_t * c, gdouble u, gdouble * s, gdouble * t)
Evaluate patch coordinates on a clipping curve
Parameters
c contains patch clipping;
u parameter on c;
s on exit contains $s(u)$ on patch;
t on exit contains $t(u)$ on patch.
Returns
0 on success.
Referenced by agg_clipping_orient().
agg_patch_map()
gint agg_patch_map (agg_patch_t * P, gdouble s, gdouble t, gdouble * u, gdouble * v)
Apply mapping in a patch to find parametric variables on surface.
Parameters
P patch whose mapping is to be applied;
s variable on P, $0\leq s \leq 1$;
t variable on P, $0\leq t \leq 1$;
u surface parametric variable;
v surface parametric variable.
Returns
0 on success.
References AGG_PATCH_BILINEAR.
Referenced by agg_clipping_orient().
agg_patch_parse()
gint agg_patch_parse (agg_patch_t * P, agg_variable_t * p, gint np)
Parse string data for an agg_patch_t.
Parameters
P on exit, is set according to input variables;
p array of variables for parameters setting P;
np number of variables in p.
Returns
0 on success.
agg_patch_st_correct()
gint agg_patch_st_correct (agg_patch_t * P, gdouble * st)
Correct out of range values of $(s,t)$ to lie in the range $(0,1)\times(0,1)$ where coordinate wrapping is permitted
Parameters
P an agg_patch_t;
st an $(s,t)$ parameter pair on patch P.
Returns
0 on success.
agg_patch_surface_diff()
gint agg_patch_surface_diff (agg_patch_t * P, gdouble s, gdouble t, gdouble * xu, gdouble * xv, gdouble * xs, gdouble * xt)
Convert derivatives with respect to surface coordinates $(u,v)$ to derivatives with respect to patch variables $(s,t)$.
Parameters
P surface patch;
s parameter on P;
t parameter on P;
xu $\partial\mathbf{x}/\partial u$ at $(u(s,t),v(s,t))$;
xv $\partial\mathbf{x}/\partial v$ at $(u(s,t),v(s,t))$;
xs on exit contains $\partial\mathbf{x}/\partial s$;
xt on exit contains $\partial\mathbf{x}/\partial t$.
Returns
0 on success.
References AGG_PATCH_BILINEAR, AGG_PATCH_SPHERICAL, and AGG_PATCH_TUBULAR.
agg_section_copy()
gint agg_section_copy (agg_section_t * dest, agg_section_t * src)
Copy one surface section into another
Parameters
dest destination section;
src source section.
Returns
0 on success, with src copied into dest.
References agg_section_close, agg_section_coefficient_lower, agg_section_coefficient_upper, agg_section_eta_left, agg_section_eta_right, agg_section_order_lower, agg_section_order_lower_max, agg_section_order_upper, agg_section_order_upper_max, agg_section_trailing_edge_lower, agg_section_trailing_edge_upper, and agg_section_type.
agg_section_diff()
gdouble agg_section_diff (agg_section_t * s, gdouble x)
Derivative of a section curve
Parameters
s a agg_section_t containing the section data;
x evaluation point $-1\leq x\leq 1$.
Returns
$y\textnormal{\textquotesingle}=\mathrm{d}f(x)/\mathrm{d}x$ on success. An error is reported and execution ceases if x is out of range or the section type is undefined.
References AGG_SECTION_AEROFOIL, AGG_SECTION_ELLIPSE, agg_section_order_lower, agg_section_order_upper, agg_section_type, and AGG_SECTION_UNDEFINED.
agg_section_eval()
gdouble agg_section_eval (agg_section_t * s, gdouble x)
Evaluate a section geometry
Parameters
s a agg_section_t containing the section data;
x evaluation point $-1\leq x\leq 1$.
Returns
$y=f(x)$ on success. An error is reported and execution ceases if x is out of range or the section type is undefined.
References AGG_SECTION_AEROFOIL, AGG_SECTION_ELLIPSE, agg_section_type, and AGG_SECTION_UNDEFINED.
agg_section_parse()
gint agg_section_parse (agg_section_t * s, gchar * name, agg_variable_t * p, gint np)
Parse an agg_section_t description given as a name and list of variable parameters
Parameters
s agg_section_t to set;
name name of section;
p array of agg_variable_t containing parameters for section;
np number of entries in p.
Returns
0 on success.
agg_section_set_aerofoil()
gint agg_section_set_aerofoil (agg_section_t * s, gdouble eta, gdouble th, gdouble yte)
Set a section to a simple aerofoil shape of specified leading edge exponent, maximum thickness, and trailing edge displacement, as in Kulfan, B. (2010). Recent extensions and applications of the `CST' universal parametric geometry representation method. The Aeronautical Journal, 114(1153), 157-176 https://doi.org/10.1017/S0001924000003614
Parameters
s agg_section_t to be initialized;
eta leading edge exponent $\eta_{1}$;
th aerofoil thickness;
yte trailing edge displacement (half trailing edge thickness).
Returns
0 on success.
References AGG_SECTION_AEROFOIL, agg_section_close, agg_section_coefficient_lower, agg_section_coefficient_upper, agg_section_eta_left, agg_section_eta_right, agg_section_order_lower, agg_section_order_upper, agg_section_trailing_edge_lower, agg_section_trailing_edge_upper, and agg_section_type.
agg_section_set_circle()
gint agg_section_set_circle (agg_section_t * s)
Set a section to a circle of radius 1/2 centred at $(0,1/2)$, as in Kulfan, B. (2010). Recent extensions and applications of the `CST' universal parametric geometry representation method. The Aeronautical Journal, 114(1153), 157-176 https://doi.org/10.1017/S0001924000003614
Parameters
s agg_section_t to be initialized;
Returns
0 on success.
References agg_section_coefficient_lower, agg_section_coefficient_upper, AGG_SECTION_ELLIPSE, agg_section_eta_left, agg_section_eta_right, agg_section_order_lower, agg_section_order_upper, and agg_section_type.
agg_sections_list()
gint agg_sections_list (FILE * f)
Write a list of available section types to output
Parameters
f output file stream.
Returns
0 on success.
agg_surface_blend_evaluate()
gint agg_surface_blend_evaluate (agg_surface_blend_t * B, gdouble s, gdouble t, gdouble * x, agg_surface_workspace_t * w)
Evaluate a surface blend, using method of Blending parametric surfaces Daniel J. Filip, ACM Transactions on Graphics, Volume 8, Issue 301, July 1989, pp164-173 https://doi.org/10.1145/77055.77057
Parameters
B surface blend, containing details of rail curves and surface to join;
s parameter $s$, $0\leq s\leq 1$
t parameter $t$, $0\leq t\leq 1$
x on exit, contains surface position at $(s,t)$;
w workspace for surface evaluation.
Returns
References agg_patch_t, and agg_surface_t.
agg_surface_patch_intersection()
gint agg_surface_patch_intersection (agg_intersection_t * inter, agg_surface_t * S1, agg_patch_t * P1, agg_surface_t * S2, agg_patch_t * P2, agg_surface_blend_t * B, agg_surface_workspace_t * w)
Calculate the intersection of two parametric surfaces.
Parameters
inter on exit contains the intersection curve data;
S1 first surface;
P1 mapping patch for first surface;
S2 second surface;
P2 mapping patch for second surface;
B if not NULL, initialized with data for blending S1 into S2 across the intersection curve;
w workspace for surface evaluation.
Returns
0 on success.
agg_surface_point_diff()
gint agg_surface_point_diff (agg_surface_t * S, gdouble u, gdouble v, gdouble * x, gdouble * xu, gdouble * xv, agg_surface_workspace_t * w)
Estimate derivatives on a surface
Parameters
S surface on which derivatives are to be evaluated;
u surface parameter;
v surface parameter;
x on exit contains $\mathbf{x}(u,v)$;
xu on exit contains $\partial\mathbf{x}/\partial u$;
xv on exit contains $\partial\mathbf{x}/\partial v$;
w workspace for surface point evaluation.
Returns
0 on success.
References agg_transform_t, and agg_variable_t.
agg_surface_point_eval()
gint agg_surface_point_eval (agg_surface_t * S, gdouble u, gdouble v, gdouble * x, agg_surface_workspace_t * w)
Evaluate a point on a surface
Evaluate a point on a surface. The surface must have been initialized with agg_surface_weights_make, and its transform initialized with agg_expression_data_compile and agg_transform_expressions_compile, to set up the internal variables and expressions used for point transformation. The section data for S are interpolated at $u$ and the point on the section evaluated at $v$. The point is then transformed using the surface transformation.
Parameters
S an agg_surface_t;
u surface parameter $u$;
v surface parameter $v$;
x on exit contains $\mathbf{x}(u,v)$;
w workspace allocated using agg_surface_workspace_new
Returns
0 on success.
References agg_section_t, agg_transform_t, and agg_variable_t.
Referenced by agg_clipping_orient().
agg_surface_section_add()
gint agg_surface_section_add (agg_surface_t * S, agg_section_t * s, gdouble u)
Add a section to a surface
Add a section to a surface at a given value of parameter $u$. The section data are copied into the surface, so the section variable s can be reused afterwards.
Parameters
S an agg_surface_t;
s an agg_section_t;
u parameter value where section is to be added.
Returns
0 on success.
agg_surface_section_interp()
gint agg_surface_section_interp (agg_surface_t * S, gdouble u, agg_section_t * s)
Interpolate section data from a surface into a local section
Interpolate section data from a surface into a local section, using Berrut and Trefethen's barycentric Lagrangian interpolation, https://dx.doi.org/10.1137/S0036144502417715
Parameters
S an agg_surface_t containing a number of sections;
u parameter at which to interpolate section;
s on exit, contains interpolated data for section at u.
Returns
0 on success, 1 if S is an empty surface.
References agg_section_t.
agg_surface_weights_make()
gint agg_surface_weights_make (agg_surface_t * S)
Generate interpolation weights for sections on a surface
Generate interpolation weights for sections on a surface, the preprocessing stage for Berrut and Trefethen's barycentric Lagrangian interpolation, https://dx.doi.org/10.1137/S0036144502417715
Parameters
S an agg_surface_t containing a number of sections.
Returns
0 on success.
agg_surface_workspace_new()
agg_surface_workspace_t * agg_surface_workspace_new (void)
Allocate a workspace for evaluation of surfaces
Returns
newly allocated workspace.
References agg_section_new().
agg_transform_add_global_variables()
gint agg_transform_add_global_variables (agg_transform_t * T, agg_variable_t * global, gint nglobal)
Add a list of global variables to the variables of a transform
Parameters
T an agg_transform_t allocated with agg_transform_new;
global array of global variables;
nglobal number of global variables.
Returns
0 on success.
References agg_expression_data_t, and agg_expression_data_variable_add().
agg_transform_apply()
gint agg_transform_apply (agg_transform_t * T, gdouble * xin, gdouble * xout)
Apply a transform to a point
Parameters
T an agg_transform_t containing the sequence of operations;
xin input point (can be the same as xout);
xout on exit contains transformed version of xin.
Returns
0 on success.
References agg_transform_operator, agg_transform_operator_apply(), and agg_transform_operator_number.
agg_transform_axes()
gint agg_transform_axes (agg_axes_t axes, gdouble * xin, gdouble * xout)
Apply an axis transform (swap) to a point
Parameters
axes an agg_axes_t for the required axis transformation;
xin input point (can be equal to xout);
xout on exit contains transformed point data.
Returns
0 on success.
References AGG_AXES_PX_PY_MZ, AGG_AXES_PX_PY_PZ, AGG_AXES_PY_PZ_PX, AGG_AXES_PZ_PX_PY, and AGG_AXES_PZ_PY_PX.
agg_transform_expressions_compile()
gint agg_transform_expressions_compile (agg_transform_t * T)
Compile expressions in a transform for future evaluation.
Parameters
T an agg_transform_t allocated with agg_transform_new;
Returns
0 on success.
References agg_expression_compile(), agg_expression_data_t, agg_expression_data_variable_add(), agg_transform_operator, agg_transform_operator_number, agg_transform_operator_parameter, agg_transform_operator_parameter_number, agg_transform_operator_t, agg_transform_variable, agg_transform_variable_number, agg_variable_definition, agg_variable_evaluator, and agg_variable_t.
agg_transform_new()
 agg_transform_t * agg_transform_new (gint nopmax)
Allocate a new agg_transform_t for transformation of geometries
Parameters
nopmax maximum number of operations in transform
Returns
newly allocated agg_transform_t
References agg_transform_operator_number, agg_transform_operator_number_max, agg_transform_operator_t, agg_transform_t, and agg_transform_variable_number.
agg_transform_operator_add()
gint agg_transform_operator_add (agg_transform_t * T, agg_operation_t op, gdouble * p, gchar ** expr, gint np)
Add an operation to a transform
Parameters
T an agg_transform_t allocated with agg_transform_new;
op a basic transform operation of type agg_operation_t;
p array of parameter values to pass to transform calculation;
expr expressions to be used in evaluating transform parameters;
np number of parameters to pass to transform.
Returns
0 on success
References agg_transform_operator, agg_transform_operator_func, agg_transform_operator_new(), agg_transform_operator_number, agg_transform_operator_operation, agg_transform_operator_parameter, agg_transform_operator_parameter_number, agg_transform_operator_t, agg_variable_definition, agg_variable_name, agg_variable_t, and agg_variable_value.
Referenced by agg_transform_parse().
agg_transform_operator_apply()
gint agg_transform_operator_apply (agg_transform_operator_t * op, gdouble * xin, gdouble * xout)
Apply a transform operation to a point.
Parameters
op transform operation (usually part of an agg_transform_t);
xin input point;
xout on exit contains transformed version of xin.
Returns
0 on success.
Referenced by agg_transform_apply().
agg_transform_operators_write()
gint agg_transform_operators_write (FILE * f, agg_transform_t * T)
Write a list of operators and parameters in a transform to file
Parameters
f file stream for output;
T the agg_transform_t to write.
Returns
0 on success.
References agg_transform_operator, agg_transform_operator_number, agg_transform_operator_operation, agg_transform_operator_parameter, agg_transform_operator_parameter_number, agg_transform_operator_t, and agg_variable_t.
agg_transform_parse()
gint agg_transform_parse (agg_transform_t * T, gchar * name, agg_variable_t * p, gint np)
Parse a transform operation described by a string and add it to an agg_transform_t
Parameters
T agg_transform_t to have an operation added;
name name of transform operation (see agg_transform_operators_write);
p array of agg_variable_t holding parameters of transform;
np number of entries in p.
Returns
0 on success.
References agg_transform_operator_add(), agg_variable_definition, and agg_variable_value.
agg_transform_variable_add()
gint agg_transform_variable_add (agg_transform_t * T, gchar * var, gchar * def, gdouble val)
Add a variable to a transform
Parameters
T an agg_transform_t allocated with agg_transform_new;
var variable name;
def variable definition (may be NULL);
val variable value (used to set variable constant if def is NULL).
Returns
0 on success
References agg_transform_variable_number, and agg_variable_t.
agg_transform_variables_eval()
gint agg_transform_variables_eval (agg_transform_t * T)
Evaluate variables in a transform. Expressions should have been compiled using agg_transform_expressions_compile
Parameters
T an agg_transform_t allocated with agg_transform_new;
Returns
0 on success.
References agg_expression_data_eval(), agg_expression_eval(), agg_transform_operator, agg_transform_operator_number, agg_transform_operator_parameter, agg_transform_operator_parameter_number, agg_transform_operator_t, agg_transform_variable, agg_transform_variable_number, agg_variable_definition, agg_variable_evaluator, agg_variable_t, and agg_variable_value.
agg_transform_variables_write()
gint agg_transform_variables_write (FILE * f, agg_transform_t * T, gboolean write_defs)
Write list of variables and values for a transform to output
Parameters
f output file stream;
T an agg_transform_t allocated with agg_transform_new;
write_defs if TRUE, output variable definitions for variables that have them.
Returns
0 on success.
References agg_transform_variable, agg_transform_variable_number, agg_variable_definition, agg_variable_name, agg_variable_t, and agg_variable_value.
agg_variable_write()
gint agg_variable_write (FILE * f, agg_variable_t * v)
Write a variable definition to file. If the variable is defined using a string expression, this is written, otherwise the constant numerical value is output.
Parameters
f output file stream;
v variable to write.
Returns
0 on success.
References agg_variable_definition, agg_variable_name, and agg_variable_value.
Variable Documentation
agg_expression_data_t
agg_expression_data_t
Data structure holding internal information for evaluation of expressions
Referenced by agg_body_globals_compile(), agg_transform_add_global_variables(), and agg_transform_expressions_compile().
agg_patch_t
agg_patch_t
Data structure for mapping of surfaces
Referenced by agg_body_new(), agg_mesh_surface_add_grid(), agg_mesh_surface_add_triangle(), agg_mesh_surface_point_add(), and agg_surface_blend_evaluate().
agg_section_t
agg_section_t
Data structure holding information for evaluation of a section
Referenced by agg_section_new(), agg_surface_new(), agg_surface_point_eval(), and agg_surface_section_interp().
agg_surface_t
agg_surface_t
Data structure to hold surfaces formed by transformation of sections
Referenced by agg_body_new(), agg_mesh_surface_point_add(), agg_surface_blend_evaluate(), and agg_surface_new().
agg_transform_operator_t
agg_transform_operator_t
Data structure for basic transform operations
Referenced by agg_transform_expressions_compile(), agg_transform_new(), agg_transform_operator_add(), agg_transform_operator_new(), agg_transform_operators_write(), and agg_transform_variables_eval().
agg_transform_t
agg_transform_t
Data structure for transformations converting sections into surfaces
Referenced by agg_surface_point_diff(), agg_surface_point_eval(), and agg_transform_new().