agg.c File Reference
Functions
gdouble agg_bernstein_basis_eval (gint n, gint r, gdouble x)
gint agg_bernstein_basis (gint n, gdouble x, gdouble *S, gdouble *dS)
Function Documentation
gint agg_bernstein_basis (gint n, gdouble x, gdouble * S, gdouble * dS)
Referenced by agg_shape_aerofoil_eval(), agg_shape_ellipse_eval(), agg_shape_fit(), and agg_shape_interval_add().
gdouble agg_bernstein_basis_eval (gint n, gint r, gdouble x)