Surface blends
Intersecting bodies are joined using smooth surface blends.
 agg_surface_blend_t * agg_surface_blend_new (void)
gint agg_hermite_eval (gdouble s, gdouble *H)
gint agg_surface_blend_evaluate (agg_surface_blend_t *B, gdouble s, gdouble t, gdouble *x, agg_surface_workspace_t *w)
Detailed Description
Intersecting bodies are joined using smooth surface blends.
Function Documentation
agg_hermite_eval()
gint agg_hermite_eval (gdouble s, gdouble * H)
Evaluate Hermite smoothing polynomials
Parameters
s argument of polynomials;
H on exit contains $H_{i}(s)$, $1\leq i\leq4$.
Returns
0 on success.
Referenced by agg_surface_blend_evaluate().
agg_surface_blend_evaluate()
gint agg_surface_blend_evaluate (agg_surface_blend_t * B, gdouble s, gdouble t, gdouble * x, agg_surface_workspace_t * w)
Evaluate a surface blend, using method of Blending parametric surfaces Daniel J. Filip, ACM Transactions on Graphics, Volume 8, Issue 301, July 1989, pp164-173 https://doi.org/10.1145/77055.77057
Parameters
B surface blend, containing details of rail curves and surface to join;
s parameter $s$, $0\leq s\leq 1$
t parameter $t$, $0\leq t\leq 1$
x on exit, contains surface position at $(s,t)$;
w workspace for surface evaluation.
Returns
References agg_curve_eval(), agg_hermite_eval(), agg_patch_point_diff(), agg_patch_t, agg_surface_blend_curve_reverse, agg_surface_blend_hole, agg_surface_blend_patch, agg_surface_blend_surface, and agg_surface_t.
agg_surface_blend_new()
 agg_surface_blend_t * agg_surface_blend_new (void)
Allocate a new blended surface
Returns
newly allocated agg_surface_blend_t
References agg_surface_blend_t.