Transformations
Geometrical transformation of cross-section shapes.
 agg_transform_operator_t * agg_transform_operator_new (void)
 agg_transform_t * agg_transform_new (gint nopmax)
gint agg_transform_variable_add (agg_transform_t *T, gchar *var, gchar *def, gdouble val)
gint agg_transform_add_global_variables (agg_transform_t *T, agg_variable_t *global, gint nglobal)
gint agg_transform_expressions_compile (agg_transform_t *T)
gint agg_transform_variables_eval (agg_transform_t *T)
gint agg_transform_variables_write (FILE *f, agg_transform_t *T, gboolean write_defs)
gint agg_transform_operator_add (agg_transform_t *T, agg_operation_t op, gdouble *p, gchar **expr, gint np)
gint agg_transform_operators_write (FILE *f, agg_transform_t *T)
gint agg_transform_operator_apply (agg_transform_operator_t *op, gdouble *xin, gdouble *xout)
gint agg_transform_apply (agg_transform_t *T, gdouble *xin, gdouble *xout)
gint agg_transform_axes (agg_axes_t axes, gdouble *xin, gdouble *xout)
 agg_axes_t agg_axes_parse (gchar *str)
gint agg_transform_parse (agg_transform_t *T, gchar *name, agg_variable_t *p, gint np)
enum agg_operation_t {
 AGG_TRANSFORM_UNDEFINED = 0
, AGG_TRANSFORM_ROTATE = 1
, AGG_TRANSFORM_SHRINK = 2
, AGG_TRANSFORM_TRANSLATE = 3
,
 AGG_TRANSFORM_SCALE = 4
, AGG_TRANSFORM_SCALE_X = 5
, AGG_TRANSFORM_SCALE_Y = 6
 }
Detailed Description
Geometrical transformation of cross-section shapes.
Enumeration Type Documentation
agg_operation_t
enum agg_operation_t
Basic transform operations
Enumerator
AGG_TRANSFORM_UNDEFINED undefined transform
AGG_TRANSFORM_ROTATE anti-clockwise rotation about a point
AGG_TRANSFORM_SHRINK scaling by contracting towards a point
AGG_TRANSFORM_TRANSLATE translation in three dimensions
AGG_TRANSFORM_SCALE scaling by multiplying a constant factor
AGG_TRANSFORM_SCALE_X scaling in x multiplying a constant factor
AGG_TRANSFORM_SCALE_Y scaling in y multiplying a constant factor
Function Documentation
agg_axes_parse()
 agg_axes_t agg_axes_parse (gchar * str)
Parse a string specifying an axis change on a surface.
Parameters
str axis string to parse
Returns
agg_axes_t corresponding to str, or AGG_AXES_UNDEFINED.
agg_transform_add_global_variables()
gint agg_transform_add_global_variables (agg_transform_t * T, agg_variable_t * global, gint nglobal)
Add a list of global variables to the variables of a transform
Parameters
T an agg_transform_t allocated with agg_transform_new;
global array of global variables;
nglobal number of global variables.
Returns
0 on success.
References agg_expression_data_t, and agg_expression_data_variable_add().
agg_transform_apply()
gint agg_transform_apply (agg_transform_t * T, gdouble * xin, gdouble * xout)
Apply a transform to a point
Parameters
T an agg_transform_t containing the sequence of operations;
xin input point (can be the same as xout);
xout on exit contains transformed version of xin.
Returns
0 on success.
References agg_transform_operator, agg_transform_operator_apply(), and agg_transform_operator_number.
Referenced by agg_section_format_write(), and agg_section_write().
agg_transform_axes()
gint agg_transform_axes (agg_axes_t axes, gdouble * xin, gdouble * xout)
Apply an axis transform (swap) to a point
Parameters
axes an agg_axes_t for the required axis transformation;
xin input point (can be equal to xout);
xout on exit contains transformed point data.
Returns
0 on success.
References AGG_AXES_PX_PY_MZ, AGG_AXES_PX_PY_PZ, AGG_AXES_PY_PZ_PX, AGG_AXES_PZ_PX_PY, and AGG_AXES_PZ_PY_PX.
agg_transform_expressions_compile()
gint agg_transform_expressions_compile (agg_transform_t * T)
Compile expressions in a transform for future evaluation.
Parameters
T an agg_transform_t allocated with agg_transform_new;
Returns
0 on success.
References agg_expression_compile(), agg_expression_data_t, agg_expression_data_variable_add(), agg_transform_operator, agg_transform_operator_number, agg_transform_operator_parameter, agg_transform_operator_parameter_number, agg_transform_operator_t, agg_transform_variable, agg_transform_variable_number, agg_variable_definition, agg_variable_evaluator, and agg_variable_t.
agg_transform_new()
 agg_transform_t * agg_transform_new (gint nopmax)
Allocate a new agg_transform_t for transformation of geometries
Parameters
nopmax maximum number of operations in transform
Returns
newly allocated agg_transform_t
References agg_transform_operator_number, agg_transform_operator_number_max, agg_transform_operator_t, agg_transform_t, and agg_transform_variable_number.
agg_transform_operator_add()
gint agg_transform_operator_add (agg_transform_t * T, agg_operation_t op, gdouble * p, gchar ** expr, gint np)
Add an operation to a transform
Parameters
T an agg_transform_t allocated with agg_transform_new;
op a basic transform operation of type agg_operation_t;
p array of parameter values to pass to transform calculation;
expr expressions to be used in evaluating transform parameters;
np number of parameters to pass to transform.
Returns
0 on success
References agg_transform_operator, agg_transform_operator_func, agg_transform_operator_new(), agg_transform_operator_number, agg_transform_operator_operation, agg_transform_operator_parameter, agg_transform_operator_parameter_number, agg_transform_operator_t, agg_variable_definition, agg_variable_name, agg_variable_t, and agg_variable_value.
Referenced by agg_transform_parse().
agg_transform_operator_apply()
gint agg_transform_operator_apply (agg_transform_operator_t * op, gdouble * xin, gdouble * xout)
Apply a transform operation to a point.
Parameters
op transform operation (usually part of an agg_transform_t);
xin input point;
xout on exit contains transformed version of xin.
Returns
0 on success.
Referenced by agg_transform_apply().
agg_transform_operator_new()
 agg_transform_operator_t * agg_transform_operator_new (void)
Allocate a new agg_transform_operator_t
This function is mainly called as part of setting up a new transform, via agg_transform_operator_add
Returns
a newly allocaed agg_transform_operator_t
References agg_transform_operator_t.
Referenced by agg_transform_operator_add().
agg_transform_operators_write()
gint agg_transform_operators_write (FILE * f, agg_transform_t * T)
Write a list of operators and parameters in a transform to file
Parameters
f file stream for output;
T the agg_transform_t to write.
Returns
0 on success.
References agg_transform_operator, agg_transform_operator_number, agg_transform_operator_operation, agg_transform_operator_parameter, agg_transform_operator_parameter_number, agg_transform_operator_t, and agg_variable_t.
agg_transform_parse()
gint agg_transform_parse (agg_transform_t * T, gchar * name, agg_variable_t * p, gint np)
Parse a transform operation described by a string and add it to an agg_transform_t
Parameters
T agg_transform_t to have an operation added;
name name of transform operation (see agg_transform_operators_write);
p array of agg_variable_t holding parameters of transform;
np number of entries in p.
Returns
0 on success.
References agg_transform_operator_add(), agg_variable_definition, and agg_variable_value.
agg_transform_variable_add()
gint agg_transform_variable_add (agg_transform_t * T, gchar * var, gchar * def, gdouble val)
Add a variable to a transform
Parameters
T an agg_transform_t allocated with agg_transform_new;
var variable name;
def variable definition (may be NULL);
val variable value (used to set variable constant if def is NULL).
Returns
0 on success
References agg_transform_variable_number, and agg_variable_t.
agg_transform_variables_eval()
gint agg_transform_variables_eval (agg_transform_t * T)
Evaluate variables in a transform. Expressions should have been compiled using agg_transform_expressions_compile
Parameters
T an agg_transform_t allocated with agg_transform_new;
Returns
0 on success.
References agg_expression_data_eval(), agg_expression_eval(), agg_transform_operator, agg_transform_operator_number, agg_transform_operator_parameter, agg_transform_operator_parameter_number, agg_transform_operator_t, agg_transform_variable, agg_transform_variable_number, agg_variable_definition, agg_variable_evaluator, agg_variable_t, and agg_variable_value.
agg_transform_variables_write()
gint agg_transform_variables_write (FILE * f, agg_transform_t * T, gboolean write_defs)
Write list of variables and values for a transform to output
Parameters
f output file stream;
T an agg_transform_t allocated with agg_transform_new;
write_defs if TRUE, output variable definitions for variables that have them.
Returns
0 on success.
References agg_transform_variable, agg_transform_variable_number, agg_variable_definition, agg_variable_name, agg_variable_t, and agg_variable_value.