Bernstein polynomials
Evaluation of Bernstein polynomials.
gdouble agg_bernstein_basis_eval (gint n, gint r, gdouble x)
gdouble agg_bernstein_derivative_eval (gint n, gint r, gdouble x)
gint agg_bernstein_basis (gint n, gdouble x, gdouble *S, gdouble *dS)
Detailed Description
Evaluation of Bernstein polynomials.
Function Documentation
agg_bernstein_basis()
gint agg_bernstein_basis (gint n, gdouble x, gdouble * S, gdouble * dS)
Evaluate all monomials of a Bernstein basis of specified degree and, optionally, their derivatives.
Parameters
n degree of Bernstein basis;
x argument of monomials;
S on exit contains $B_{r}^{(n)}(x)$, $0\leq r\leq n$;
dS if not NULL, on exit contains $\mathrm{d}B_{r}^{(n)}(x)/\mathrm{d}x$, $0\leq r\leq n$.
Returns
0 on success
Referenced by agg_section_fit().
agg_bernstein_basis_eval()
gdouble agg_bernstein_basis_eval (gint n, gint r, gdouble x)
Evaluate a Bernstein basis monomial, $B_{r}^{(n)}(x)=\binom{n}{r}x^{r}(1-x)^{n-r}$
Parameters
n degree of Bernstein basis;
r mononomial from basis to evaluate;
x argument of monomial
Returns
$B_{r}^{(n)}(x)$
Referenced by agg_section_diff(), and agg_section_eval().
agg_bernstein_derivative_eval()
gdouble agg_bernstein_derivative_eval (gint n, gint r, gdouble x)
Evaluate the derivative of a Bernstein monomial $\mathrm{d}B_{r}^{(n)}(x)/\mathrm{d}x$
Parameters
n degree of Bernstein basis;
r mononomial from basis to evaluate;
x argument of monomial
Returns
$\mathrm{d}B_{r}^{(n)}(x)/\mathrm{d}x$
Referenced by agg_section_diff().