One-dimensional curves
Single-parameter curves used to cut surfaces or define boundaries.
gint agg_curve_eval (agg_curve_t *c, gdouble x, gdouble *s, gdouble *t)
gint agg_curve_plane_normal (agg_curve_t *c, agg_surface_t *S, agg_patch_t *P, gdouble *n, agg_surface_workspace_t *w)
Detailed Description
Single-parameter curves used to cut surfaces or define boundaries.
Function Documentation
agg_curve_eval()
gint agg_curve_eval (agg_curve_t * c, gdouble x, gdouble * s, gdouble * t)
Evaluate coordinates on a parameterized curve
Parameters
c agg_curve_t to be evaluated;
x parameter on c;
s on exit, set to $s$ in parametric plane;
t on exit, set to $t$ in parametric plane.
Returns
0 on success.
References AGG_CURVE_FOURIER.
Referenced by agg_curve_plane_normal(), and agg_surface_blend_evaluate().
agg_curve_plane_normal()
gint agg_curve_plane_normal (agg_curve_t * c, agg_surface_t * S, agg_patch_t * P, gdouble * n, agg_surface_workspace_t * w)
Estimate a normal to the plane approximately containing a curve on a surface. This is a rough estimate intended to be used in checking curve orientations.
Parameters
c an agg_curve_t;
S surface on which curve is defined;
P patch for mapping c onto S;
n on exit contains estimated normal;
w workspace for surface evaluation.
Returns
0 on success.
References agg_curve_eval(), agg_patch_map(), and agg_surface_point_eval().