Surface patches
Patches used to map parts of surfaces and generate meshes.
 agg_patch_t * agg_patch_new (void)
gint agg_patch_map (agg_patch_t *P, gdouble s, gdouble t, gdouble *u, gdouble *v)
gint agg_patch_parse (agg_patch_t *P, agg_variable_t *p, gint np)
gint agg_patch_surface_diff (agg_patch_t *P, gdouble s, gdouble t, gdouble *xu, gdouble *xv, gdouble *xs, gdouble *xt)
gint agg_patch_point_diff (agg_surface_t *S, agg_patch_t *P, gdouble s, gdouble t, gdouble *x, gdouble *xs, gdouble *xt, agg_surface_workspace_t *w)
gint agg_patch_edge_split (agg_patch_t *P, gdouble s0, gdouble t0, gdouble s1, gdouble t1, gdouble a, gdouble *s, gdouble *t)
gint agg_patch_triangle_interp (agg_patch_t *P, gdouble s0, gdouble t0, gdouble s1, gdouble t1, gdouble s2, gdouble t2, gdouble u, gdouble v, gdouble *s, gdouble *t)
enum agg_patch_mapping_t { AGG_PATCH_BILINEAR = 0
, AGG_PATCH_SPHERICAL = 1
, AGG_PATCH_HEMISPHERICAL = 2
, AGG_PATCH_TUBULAR = 3
 }
Detailed Description
Patches used to map parts of surfaces and generate meshes.
Enumeration Type Documentation
agg_patch_mapping_t
enum agg_patch_mapping_t
Mappings from $(s,t)$ on a patch to $(u,v)$ on a surface
Enumerator
AGG_PATCH_BILINEAR bilinear mapping between corners
AGG_PATCH_SPHERICAL mapping to surface of sphere
AGG_PATCH_HEMISPHERICAL mapping to surface of hemisphere
AGG_PATCH_TUBULAR mapping to surface of open cylinder
Function Documentation
agg_patch_edge_split()
gint agg_patch_edge_split (agg_patch_t * P, gdouble s0, gdouble t0, gdouble s1, gdouble t1, gdouble a, gdouble * s, gdouble * t)
Split an edge, the line segment joining two points in $(s,t)$ parametric plane, remapping as required to respect the underlying mapping of the patch. For a linear patch $s=s_{0}+a(s_{1}-s_{0})$, $t=t_{0}+a(t_{1}-t_{0})$; for other mappings, such as spherical or hemispherical, the interpolation is different.
Parameters
P surface mapping patch;
s0 coordinate of first point on segment;
t0 coordinate of first point on segment;
s1 coordinate of second point on segment;
t1 coordinate of second point on segment;
a parametric distance on segment;
s on output, coordinate of interpolated point on segment;
t on output, coordinate of interpolated point on segment.
Returns
0 on success.
References AGG_PATCH_SPHERICAL.
agg_patch_map()
gint agg_patch_map (agg_patch_t * P, gdouble s, gdouble t, gdouble * u, gdouble * v)
Apply mapping in a patch to find parametric variables on surface.
Parameters
P patch whose mapping is to be applied;
s variable on P, $0\leq s \leq 1$;
t variable on P, $0\leq t \leq 1$;
u surface parametric variable;
v surface parametric variable.
Returns
0 on success.
References AGG_PATCH_BILINEAR.
Referenced by agg_curve_plane_normal(), and agg_patch_point_diff().
agg_patch_new()
 agg_patch_t * agg_patch_new (void)
Allocate a new patch for mapping of surface parameters
Returns
newly allocated agg_patch_t
References agg_curve_data, agg_curve_order, AGG_CURVE_POLYNOMIAL, AGG_PATCH_BILINEAR, and agg_patch_t.
agg_patch_parse()
gint agg_patch_parse (agg_patch_t * P, agg_variable_t * p, gint np)
Parse string data for an agg_patch_t.
Parameters
P on exit, is set according to input variables;
p array of variables for parameters setting P;
np number of variables in p.
Returns
0 on success.
agg_patch_point_diff()
gint agg_patch_point_diff (agg_surface_t * S, agg_patch_t * P, gdouble s, gdouble t, gdouble * x, gdouble * xs, gdouble * xt, agg_surface_workspace_t * w)
Estimate the derivatives on a surface with respect to parametric coordinates $(s,t)$.
Parameters
S surface to differentiate;
P mapping patch;
s coordinate on P;
t coordinate on P;
x on exit, contains point $\mathbf{x}(u(s,t),v(s,t))$;
xs on exit, contains $\partial\mathbf{x}(u(s,t),v(s,t))/\partial s$;
xt on exit, contains $\partial\mathbf{x}(u(s,t),v(s,t))/\partial t$;
w workspace for surface evaluation.
Returns
0 on success.
References agg_patch_map(), and agg_surface_point_eval().
Referenced by agg_surface_blend_evaluate().
agg_patch_surface_diff()
gint agg_patch_surface_diff (agg_patch_t * P, gdouble s, gdouble t, gdouble * xu, gdouble * xv, gdouble * xs, gdouble * xt)
Convert derivatives with respect to surface coordinates $(u,v)$ to derivatives with respect to patch variables $(s,t)$.
Parameters
P surface patch;
s parameter on P;
t parameter on P;
xu $\partial\mathbf{x}/\partial u$ at $(u(s,t),v(s,t))$;
xv $\partial\mathbf{x}/\partial v$ at $(u(s,t),v(s,t))$;
xs on exit contains $\partial\mathbf{x}/\partial s$;
xt on exit contains $\partial\mathbf{x}/\partial t$.
Returns
0 on success.
References AGG_PATCH_BILINEAR, AGG_PATCH_SPHERICAL, and AGG_PATCH_TUBULAR.
agg_patch_triangle_interp()
gint agg_patch_triangle_interp (agg_patch_t * P, gdouble s0, gdouble t0, gdouble s1, gdouble t1, gdouble s2, gdouble t2, gdouble u, gdouble v, gdouble * s, gdouble * t)
Split a triangle in the parametric plane, remapping as required to respect the underlying mapping of the patch.
Parameters
P surface mapping patch;
s0 coordinate of first point on triangle;
t0 coordinate of first point on triangle;
s1 coordinate of second point on triangle;
t1 coordinate of second point on triangle;
s2 coordinate of third point on triangle;
t2 coordinate of third point on triangle;
u coordinate on triangle;
v coordinate on triangle;
s on output, coordinate of interpolated point on triangle;
t on output, coordinate of interpolated point on triangle.
Returns
0 on success.
References AGG_PATCH_SPHERICAL.