General bodies
Bodies are made up of collections of elementary surfaces.
 agg_body_t * agg_body_new (gint ngmax, gint nsmax)
gint agg_body_global_add (agg_body_t *b, gchar *var, gchar *def, gdouble val)
gint agg_body_globals_write (FILE *f, agg_body_t *b)
gint agg_body_globals_compile (agg_body_t *b)
gint agg_body_globals_eval (agg_body_t *b)
gint agg_body_read (agg_body_t *b, gchar *file, gboolean echo)
gint agg_body_surfaces_list (FILE *f, agg_body_t *b)
typedef agg_body_t
Detailed Description
Bodies are made up of collections of elementary surfaces.
Function Documentation
agg_body_global_add()
gint agg_body_global_add (agg_body_t * b, gchar * var, gchar * def, gdouble val)
Add a global variable to an agg_body_t
Parameters
b body to which variable should be added;
var name of variable;
def string expression defining variable (can be NULL);
val value of variable (set constant if expr is NULL).
Returns
0 on success.
References agg_variable_definition, agg_variable_name, agg_variable_t, and agg_variable_value.
agg_body_globals_compile()
gint agg_body_globals_compile (agg_body_t * b)
Compile expressions for global variables in an agg_body_t. This function should be called before evaluating any variables in the body or its surfaces.
Parameters
b an agg_body_t containing definitions of global variables.
Returns
0 on success.
References agg_expression_compile(), agg_expression_data_t, agg_expression_data_variable_add(), agg_variable_definition, agg_variable_evaluator, and agg_variable_t.
agg_body_globals_eval()
gint agg_body_globals_eval (agg_body_t * b)
Evaluate global variables defined in an agg_body_t. This function should be called before evaluating points on the surfaces which make up the body.
Parameters
b an agg_body_t containing global variables.
Returns
0 on success.
References agg_expression_data_eval(), agg_expression_eval(), agg_variable_definition, agg_variable_evaluator, agg_variable_t, and agg_variable_value.
agg_body_globals_write()
gint agg_body_globals_write (FILE * f, agg_body_t * b)
Write a body's global variables, their definitions (if given), and values to file
Parameters
f output file;
b agg_body_t whose global variables are to be written
Returns
0 on success.
References agg_variable_definition, agg_variable_name, agg_variable_t, and agg_variable_value.
agg_body_new()
 agg_body_t * agg_body_new (gint ngmax, gint nsmax)
Allocate and initialize a new agg_body_t
Parameters
ngmax maximum number of global variables in body;
nsmax maximum number of surfaces in body.
Returns
newly allocated agg_body_t
References agg_body_t, agg_patch_t, agg_surface_t, and agg_variable_t.
agg_body_read()
gint agg_body_read (agg_body_t * b, gchar * file, gboolean echo)
Read an agg_body_t from file
Parameters
b body to which data in file are to be added;
file name of file in .agg format;
echo if TRUE, echo progress to stderr.
Returns
0 on success.
References agg_section_new().
agg_body_surfaces_list()
gint agg_body_surfaces_list (FILE * f, agg_body_t * b)
Write the names of a body's surfaces to file
Parameters
f output file stream;
b an agg_body_t whose surfaces are to be listed.
Returns
0 on success.
Variable Documentation
agg_body_t
agg_body_t
Data structure for bodies made up of collections of surfaces
Referenced by agg_body_new().