Variables and expressions
Symbolically defined variables and expressions.
gint agg_expression_data_variable_add (agg_expression_data_t *d, agg_variable_t *v)
gpointer agg_expression_compile (gchar *e, agg_expression_data_t *d)
gdouble agg_expression_eval (gpointer e)
gint agg_expression_data_compile (agg_expression_data_t *d)
gint agg_expression_data_eval (agg_expression_data_t *d)
gint agg_variable_write (FILE *f, agg_variable_t *v)
typedef agg_variable_t
Detailed Description
Symbolically defined variables and expressions.
Function Documentation
agg_expression_compile()
gpointer agg_expression_compile (gchar * e, agg_expression_data_t * d)
Compile a symbolically defined expression, for future evaluation
Parameters
e the expression to be compiled;
d structure holding variable data.
Returns
pointer to compiled expression.
Referenced by agg_body_globals_compile(), and agg_transform_expressions_compile().
agg_expression_data_compile()
gint agg_expression_data_compile (agg_expression_data_t * d)
Compile expressions in an expression data structure, for future evaluation
Parameters
d an agg_expression_data_t
Returns
0 on success.
agg_expression_data_eval()
gint agg_expression_data_eval (agg_expression_data_t * d)
Evaluate expressions in an expression data structure, making the values available for other calculations.
Parameters
d an agg_expression_data_t whose expressions are to be evaluated.
Returns
0 on success.
Referenced by agg_body_globals_eval(), and agg_transform_variables_eval().
agg_expression_data_variable_add()
gint agg_expression_data_variable_add (agg_expression_data_t * d, agg_variable_t * v)
Add a variable to an agg_expression_data_t.
Parameters
d agg_expression_data_t to have variable added;
v a variable to be added to d; this may depend on variables already in d, but not on variables yet to be added.
Returns
0 on success.
References agg_variable_definition, agg_variable_name, and agg_variable_value.
Referenced by agg_body_globals_compile(), agg_transform_add_global_variables(), and agg_transform_expressions_compile().
agg_expression_eval()
gdouble agg_expression_eval (gpointer e)
Evaluate a compiled expression
Parameters
e a pointer to a tinyexpr expression
Returns
the value of e.
Referenced by agg_body_globals_eval(), and agg_transform_variables_eval().
agg_variable_write()
gint agg_variable_write (FILE * f, agg_variable_t * v)
Write a variable definition to file. If the variable is defined using a string expression, this is written, otherwise the constant numerical value is output.
Parameters
f output file stream;
v variable to write.
Returns
0 on success.
References agg_variable_definition, agg_variable_name, and agg_variable_value.
Variable Documentation
agg_variable_t
agg_variable_t
Data structure holding variable names, values, and symbolic definitions
Referenced by agg_body_global_add(), agg_body_globals_compile(), agg_body_globals_eval(), agg_body_globals_write(), agg_body_new(), agg_surface_point_eval(), agg_transform_expressions_compile(), agg_transform_operator_add(), agg_transform_operators_write(), agg_transform_variable_add(), agg_transform_variables_eval(), and agg_transform_variables_write().