mesh.c File Reference
Functions
gint agg_distribution_write_mesh (FILE *f, agg_distribution_t *d, gdouble smin, gdouble smax, gint ns, agg_spacing_t ss, gdouble tmin, gdouble tmax, gint nt, agg_spacing_t st, agg_shape_t *sh, agg_local_transform_t *T, agg_parser_t *p)
gint agg_distribution_mesh (agg_distribution_t *d, gdouble smin, gdouble smax, gint ns, agg_spacing_t ss, gdouble tmin, gdouble tmax, gint nt, agg_spacing_t st, agg_shape_t *sh, agg_local_transform_t *T, agg_parser_t *p, gdouble *x, gint xstr, gint *tr, gint tstr, gint *idx0)
gint agg_mesh_points_write (FILE *f, gdouble *x, gint str, gint n)
gint agg_mesh_tri_write (FILE *f, gint *tr, gint str, gint n)
Function Documentation
gint agg_distribution_mesh (agg_distribution_t * d, gdouble smin, gdouble smax, gint ns, agg_spacing_t ss, gdouble tmin, gdouble tmax, gint nt, agg_spacing_t st, agg_shape_t * sh, agg_local_transform_t * T, agg_parser_t * p, gdouble * x, gint xstr, gint * tr, gint tstr, gint * idx0)
gint agg_distribution_write_mesh (FILE * f, agg_distribution_t * d, gdouble smin, gdouble smax, gint ns, agg_spacing_t ss, gdouble tmin, gdouble tmax, gint nt, agg_spacing_t st, agg_shape_t * sh, agg_local_transform_t * T, agg_parser_t * p)
References agg_distribution_interpolate(), agg_local_transform_apply(), agg_local_transform_eval_parameters(), AGG_PARSER_PARAMETER_RESERVED_T, agg_shape_eval(), agg_spacing_eval(), _agg_shape_t::closed, s, _agg_distribution_t::t, and _agg_parser_t::values.
gint agg_mesh_points_write (FILE * f, gdouble * x, gint str, gint n)
gint agg_mesh_tri_write (FILE * f, gint * tr, gint str, gint n)