naca.c File Reference
Functions
gdouble agg_naca_four (gdouble t, gdouble p, gdouble m, gdouble x)
gint agg_shape_fit_naca_four (agg_shape_t *s, gint n, gdouble th, gdouble p, gdouble m, gint nu, gint nl, gdouble *work)
Function Documentation
gdouble agg_naca_four (gdouble t, gdouble p, gdouble m, gdouble x)
References a.
Referenced by agg_shape_fit_naca_four().
gint agg_shape_fit_naca_four (agg_shape_t * s, gint n, gdouble th, gdouble p, gdouble m, gint nu, gint nl, gdouble * work)
References agg_naca_four(), and agg_shape_fit().