shape.c File Reference
Macros
#define M411 0
#define M412 1
#define M413 2
#define M414 3
#define M421 4
#define M422 5
#define M423 6
#define M424 7
#define M431 8
#define M432 9
#define M433 10
#define M434 11
#define M441 12
#define M442 13
#define M443 14
#define M444 15
Functions
gdouble agg_shape_eval (agg_shape_t *s, gdouble x, gint lim)
gdouble agg_shape_aerofoil_eval (agg_shape_t *s, gdouble x)
gdouble agg_shape_ellipse_eval (agg_shape_t *s, gdouble x, gint b)
agg_shape_t * agg_shape_alloc (gint nsmax)
gint agg_shape_naca (agg_shape_t *s, gdouble t)
gint agg_shape_ellipse (agg_shape_t *s)
gint agg_shape_fit (agg_shape_t *s, gdouble *xu, gdouble *yu, gint nu, gdouble *xl, gdouble *yl, gint nl, gdouble n1, gdouble n2, gdouble d, gint n, gboolean closed, gdouble *work)
gint agg_shape_root_fit (agg_shape_t *s, gdouble n1, gdouble n2, gdouble hu, gdouble su, gdouble du, gdouble bu, gdouble hl, gdouble sl, gdouble dl, gdouble bl, gint n, gdouble *work)
gint agg_shape_interval_add (agg_shape_t *s, gdouble x1, gdouble x2, gdouble *x, gdouble *y, gint np, gboolean upper, gdouble n1, gdouble n2, gint n, gdouble *work)
gint agg_shape_parse (agg_shape_t *s, gchar *type, gdouble *p, gint np)
gint agg_shape_copy (agg_shape_t *dest, agg_shape_t *src)
Macro Definition Documentation
#define M411 0
#define M412 1
#define M413 2
#define M414 3
#define M421 4
#define M422 5
#define M423 6
#define M424 7
#define M431 8
#define M432 9
#define M433 10
#define M434 11
#define M441 12
#define M442 13
#define M443 14
#define M444 15
Function Documentation
gdouble agg_shape_aerofoil_eval (agg_shape_t * s, gdouble x)
References agg_bernstein_basis(), _agg_shape_t::i, _agg_shape_t::n1, _agg_shape_t::n2, _agg_shape_t::nb, and _agg_shape_t::s.
Referenced by agg_shape_eval().
agg_shape_t* agg_shape_alloc (gint nsmax)
References _agg_shape_t::b, _agg_shape_t::nsmax, s, and _agg_shape_t::s.
gint agg_shape_copy (agg_shape_t * dest, agg_shape_t * src)
References _agg_shape_t::b, _agg_shape_t::closed, _agg_shape_t::i, _agg_shape_t::n1, _agg_shape_t::n2, _agg_shape_t::nb, _agg_shape_t::nsmax, _agg_shape_t::s, and _agg_shape_t::type.
gint agg_shape_ellipse (agg_shape_t * s)
References AGG_SHAPE_ELLIPSE, _agg_shape_t::b, _agg_shape_t::closed, _agg_shape_t::i, _agg_shape_t::n1, _agg_shape_t::n2, _agg_shape_t::nb, _agg_shape_t::s, and _agg_shape_t::type.
Referenced by agg_shape_parse().
gdouble agg_shape_ellipse_eval (agg_shape_t * s, gdouble x, gint b)
References agg_bernstein_basis(), agg_shape_break_lower, agg_shape_break_number, agg_shape_break_upper, _agg_shape_t::i, _agg_shape_t::n1, _agg_shape_t::n2, and _agg_shape_t::s.
Referenced by agg_shape_eval().
gdouble agg_shape_eval (agg_shape_t * s, gdouble x, gint lim)
References AGG_SHAPE_AEROFOIL, agg_shape_aerofoil_eval(), AGG_SHAPE_ELLIPSE, agg_shape_ellipse_eval(), and _agg_shape_t::type.
Referenced by agg_distribution_write_mesh(), and agg_shape_interpolant_make().
gint agg_shape_fit (agg_shape_t * s, gdouble * xu, gdouble * yu, gint nu, gdouble * xl, gdouble * yl, gint nl, gdouble n1, gdouble n2, gdouble d, gint n, gboolean closed, gdouble * work)
References agg_bernstein_basis(), _agg_shape_t::closed, _agg_shape_t::i, _agg_shape_t::n1, _agg_shape_t::n2, _agg_shape_t::nsmax, and _agg_shape_t::s.
Referenced by agg_shape_fit_naca_four().
gint agg_shape_interval_add (agg_shape_t * s, gdouble x1, gdouble x2, gdouble * x, gdouble * y, gint np, gboolean upper, gdouble n1, gdouble n2, gint n, gdouble * work)
References agg_bernstein_basis(), _agg_shape_t::b, _agg_shape_t::i, _agg_shape_t::n1, _agg_shape_t::n2, _agg_shape_t::nb, np, and _agg_shape_t::s.
Referenced by agg_shape_root_fit().
gint agg_shape_naca (agg_shape_t * s, gdouble t)
References AGG_SHAPE_AEROFOIL, _agg_shape_t::b, _agg_shape_t::closed, _agg_shape_t::i, _agg_shape_t::n1, _agg_shape_t::n2, _agg_shape_t::nb, _agg_shape_t::s, and _agg_shape_t::type.
gint agg_shape_parse (agg_shape_t * s, gchar * type, gdouble * p, gint np)
References agg_shape_ellipse(), agg_shape_root_fit(), defaults, _agg_shape_t::n1, _agg_shape_t::n2, _agg_shape_t::s, and shape.
gint agg_shape_root_fit (agg_shape_t * s, gdouble n1, gdouble n2, gdouble hu, gdouble su, gdouble du, gdouble bu, gdouble hl, gdouble sl, gdouble dl, gdouble bl, gint n, gdouble * work)
References AGG_SHAPE_ELLIPSE, agg_shape_interval_add(), _agg_shape_t::b, _agg_shape_t::closed, _agg_shape_t::i, _agg_shape_t::nb, np, and _agg_shape_t::type.
Referenced by agg_shape_parse().
Variable Documentation
gboolean defaults
Referenced by agg_shape_parse().
gint np
Referenced by agg_shape_interval_add(), and agg_shape_root_fit().
gchar* shape
Referenced by agg_shape_parse().