tinyexpr.c File Reference
Data Structures
struct state
Macros
#define TE_NAT_LOG
#define NAN (0.0/0.0)
#define INFINITY (1.0/0.0)
#define TYPE_MASK(TYPE) ((TYPE)&0x0000001F)
#define IS_PURE(TYPE) (((TYPE) & TE_FLAG_PURE) != 0)
#define IS_FUNCTION(TYPE) (((TYPE) & TE_FUNCTION0) != 0)
#define IS_CLOSURE(TYPE) (((TYPE) & TE_CLOSURE0) != 0)
#define ARITY(TYPE) (((TYPE) & (TE_FUNCTION0 | TE_CLOSURE0)) ? ((TYPE) & 0x00000007) : 0)
#define NEW_EXPR(type, ...) new_expr((type), (const te_expr*[]){__VA_ARGS__})
#define TE_FUN(...) ((double(*)(__VA_ARGS__))n->function)
#define M(e) te_eval(n->parameters[e])
Typedefs
typedef double(* te_fun2) (double, double)
typedef struct state state
Enumerations
enum {
*
TOK_NULL = TE_CLOSURE7+1,
TOK_ERROR,
TOK_END,
TOK_SEP,
*
TOK_OPEN,
TOK_CLOSE,
TOK_NUMBER,
TOK_VARIABLE,
*
TOK_INFIX
 }
enum { TE_CONSTANT = 1
 }
Functions
void te_free_parameters (te_expr *n)
void te_free (te_expr *n)
void next_token (state *s)
double te_eval (const te_expr *n)
te_expr * te_compile (const char *expression, const te_variable *variables, int var_count, int *error)
double te_interp (const char *expression, int *error)
void te_print (const te_expr *n)
Macro Definition Documentation
#define ARITY(TYPE) (((TYPE) & (TE_FUNCTION0 | TE_CLOSURE0)) ? ((TYPE) & 0x00000007) : 0)
Referenced by te_eval().
#define INFINITY (1.0/0.0)
#define IS_CLOSURE(TYPE) (((TYPE) & TE_CLOSURE0) != 0)
#define IS_FUNCTION(TYPE) (((TYPE) & TE_FUNCTION0) != 0)
#define IS_PURE(TYPE) (((TYPE) & TE_FLAG_PURE) != 0)
#define M(e) te_eval(n->parameters[e])
Referenced by te_eval().
#define NAN (0.0/0.0)
Referenced by te_eval(), and te_interp().
#define NEW_EXPR(type, ...) new_expr((type), (const te_expr*[]){__VA_ARGS__})
#define TE_FUN(...) ((double(*)(__VA_ARGS__))n->function)
Referenced by te_eval().
#define TE_NAT_LOG
#define TYPE_MASK(TYPE) ((TYPE)&0x0000001F)
Referenced by next_token(), te_eval(), and te_free_parameters().
Typedef Documentation
typedef struct state state
typedef double(* te_fun2) (double, double)
Enumeration Type Documentation
anonymous enum
Enumerator
TOK_NULL
TOK_ERROR
TOK_END
TOK_SEP
TOK_OPEN
TOK_CLOSE
TOK_NUMBER
TOK_VARIABLE
TOK_INFIX
anonymous enum
Enumerator
TE_CONSTANT
Function Documentation
void next_token (state * s)
References state::bound, state::context, state::function, state::next, TOK_CLOSE, TOK_END, TOK_ERROR, TOK_INFIX, TOK_NULL, TOK_NUMBER, TOK_OPEN, TOK_SEP, TOK_VARIABLE, state::type, TYPE_MASK, and state::value.
Referenced by te_compile().
te_expr* te_compile (const char * expression, const te_variable * variables, int var_count, int * error)
References state::lookup, state::lookup_len, state::next, next_token(), s, state::start, te_free(), TOK_END, and state::type.
Referenced by agg_local_transform_set_expression(), agg_parser_declaration(), agg_parser_expression_add(), and te_interp().
double te_eval (const te_expr * n)
References ARITY, M, NAN, TE_CONSTANT, TE_FUN, and TYPE_MASK.
Referenced by agg_functions_eval(), agg_local_transform_eval_parameters(), agg_parser_expressions_evaluate(), and te_interp().
void te_free (te_expr * n)
References te_free_parameters().
Referenced by te_compile(), te_free_parameters(), and te_interp().
void te_free_parameters (te_expr * n)
References te_free(), and TYPE_MASK.
Referenced by te_free().
double te_interp (const char * expression, int * error)
References NAN, te_compile(), te_eval(), and te_free().
void te_print (const te_expr * n)