transform.c File Reference
Functions
gint agg_local_transform_init (agg_local_transform_t *t)
agg_local_transform_t * agg_local_transform_alloc (void)
gint agg_local_transform_rotate (gdouble *x, gdouble *p, gdouble *y)
gint agg_local_transform_shift (gdouble *x, gdouble *p, gdouble *y)
gint agg_local_transform_scale (gdouble *x, gdouble *p, gdouble *y)
gint agg_local_transform_shrink (gdouble *x, gdouble *p, gdouble *y)
gint agg_local_transform_parse (agg_local_transform_t *T, gchar *type, gdouble *p, gint np)
gint agg_local_transform_apply (agg_local_transform_t *T, gdouble *y)
Function Documentation
agg_local_transform_t* agg_local_transform_alloc (void)
References agg_local_transform_init().
gint agg_local_transform_apply (agg_local_transform_t * T, gdouble * y)
References _agg_local_transform_t::func, _agg_local_transform_t::nt, _agg_local_transform_t::p, _agg_local_transform_t::p1, and s.
Referenced by agg_distribution_write_mesh().
gint agg_local_transform_init (agg_local_transform_t * t)
References AGG_TRANSFORM_PARAMETER_NUMBER, _agg_local_transform_t::isexpr, _agg_local_transform_t::nt, and _agg_local_transform_t::p1.
Referenced by agg_local_transform_alloc().
gint agg_local_transform_parse (agg_local_transform_t * T, gchar * type, gdouble * p, gint np)
References _agg_local_transform_t::func, np, _agg_local_transform_t::nt, _agg_local_transform_t::p, _agg_local_transform_t::p1, and transform.
gint agg_local_transform_rotate (gdouble * x, gdouble * p, gdouble * y)
gint agg_local_transform_scale (gdouble * x, gdouble * p, gdouble * y)
gint agg_local_transform_shift (gdouble * x, gdouble * p, gdouble * y)
gint agg_local_transform_shrink (gdouble * x, gdouble * p, gdouble * y)
Variable Documentation
agg_local_transform_func_t func
Referenced by agg_parser_function_add().
gint np
Referenced by agg_local_transform_parse().
gchar* transform
Referenced by agg_local_transform_parse().